name: Deploy to Beanstalk
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - uses: benjlevesque/short-sha@v1.2
          id: short-sha
          with:
            length: 8

      - name: Generate deployment package
        run: git archive --format=zip HEAD -o ipfs-proxy@${{ steps.short-sha.outputs.sha }}.zip

      - name: Deploy primary
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ipfs-proxy
          environment_name: ipfs-proxy-prod
          region: us-east-2
          version_label: ipfs-proxy@${{ steps.short-sha.outputs.sha }}
          version_description: ${{ github.event.head_commit.message }}
          use_existing_version_if_available: true
          deployment_package: ipfs-proxy@${{ steps.short-sha.outputs.sha }}.zip

      - name: Deploy secondary
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ipfs-proxy
          environment_name: ipfs-proxy-prod-2
          region: us-east-2
          version_label: ipfs-proxy@${{ steps.short-sha.outputs.sha }}
          version_description: ${{ github.event.head_commit.message }}
          use_existing_version_if_available: true
          deployment_package: ipfs-proxy@${{ steps.short-sha.outputs.sha }}.zip
